# Generated by Django 2.2.1 on 2019-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name2', models.CharField(max_length=20)),
                ('filelink', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=140)),
                ('time', models.CharField(max_length=20, null=True)),
                ('is_img', models.BooleanField(default=False)),
            ],
        ),
    ]
