# Generated by Django 2.2.1 on 2019-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name2', models.CharField(max_length=20)),
                ('filelink', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name1', models.CharField(max_length=20)),
                ('imglink', models.CharField(max_length=40)),
            ],
        ),
    ]
